name: shopbase_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  credit_card_type_detector: ^3.0.0
  dot_navigation_bar: ^1.0.2
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flip_card: ^0.7.0
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.2.18
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^17.0.1
  flutter_rating_stars: ^1.1.0
  file_picker: ^8.0.3
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_messaging: ^14.6.5
  firebase_performance: ^0.9.4+5
  firebase_storage: ^11.7.5
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.18.0
  intl_phone_field: ^3.2.0
  go_router: ^14.0.2
  google_sign_in: ^6.2.1
  like_button: ^2.0.5
  patterns_canvas: ^0.4.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  slider_button: ^2.1.0
  smooth_page_indicator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  background_color: "#ffffff"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 19

flutter_native_splash:
  image: 'assets/icons/app_icon.png'
  color: "#FFFFFF"
  #  background_image: "assets/icons/app_icon.png"
  android: true
  ios: true
  web: true

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/active_icons/
    - assets/icons/inactive_icons/
    - assets/icons/app_icon.png
    - assets/icons/checked.png
    - assets/icons/chip.png
    - assets/icons/contact_less.png
    - assets/icons/mastercard.png
    - assets/icons/logo_google.png
    - assets/images/
    - assets/gif/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          style: italic

flutter_intl:
  enabled: true